export enum TYPE_POKEMON_SPANISH {
  dark = 'siniestro',
  electric = 'eléctrico',
  grass = 'planta',
  bug = 'bicho',
  dragon = 'dragón',
  steel = 'acero',
  fairy = 'hada',
  fighting = 'lucha',
  fire = 'fuego',
  ice = 'hielo',
  ground = 'tierra',
  ghost = 'fantasma',
  psychic = 'psíquico',
  flying = 'volador',
  normal = 'normal',
  poison = 'veneno',
  rock = 'roca',
  water = 'agua'
}
